# Rename this file to languages.toml to enable multilingual support
[zh-cn]
languageName = "ç®€ä½“ä¸­æ–‡"
languagedirection = "ltr"
title = "CodeGlimpseçš„ä¸ªäººåšå®¢"
contentDir = "content/zh-cn"
weight = 1
    [zh-cn.params.sidebar]
        subtitle = "æˆ‘çš„æ•°å­—èŠ±å›­ ğŸŒ± - åŸºäº GitHub Pages æ­å»ºçš„åšå®¢ä¸æ–‡æ¡£ã€‚æ¬¢è¿åˆ†äº«æƒ³æ³•ï¼"

[en]
languageName = "English"
languagedirection = "ltr"
title = "Personal Blogs for CodeGlimpse"
contentDir = "content/en"
weight = 2
    [en.params.sidebar]
        subtitle = "My digital garden ğŸŒ± - A blog and docs built with GitHub Pages. Thoughts welcome!"
